import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased `}
			>
				<div className="bg-gray-500 pt-40 min-h-screen pb-50">
					<h1 className="text-5xl text-center text-yellow-200">
						Planets of Star Wars
					</h1>
					{children}
				</div>
			</body>
		</html>
	);
}
